input_folder: "./input_data"
output_file: "./output/merged_data.csv"
lines_to_skip: 2
timestamp_column: "DateTime"
timestamp_format: "%Y/%m/%d %H:%M"
date_column: "Date"
date_format: "%Y/%m/%d"
time_column: "Time"
time_format: "%H:%M" 